# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(ELASTICA_HOST)%', port: '%env(ELASTICA_PORT)%' }
    indexes:
        fiction:
            index_name: fiction_%kernel.environment%
            types:
                fiction:
                    properties:
                        id: ~
                        titre: ~
                        description: ~
                        projets: ~
#                        inscrits: ~
#                        personnages: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Concept\Fiction
                        provider: ~
                        finder: ~
        personnage:
            index_name: personnage_%kernel.environment%
            types:
                personnage:
                    properties:
                        id: ~
                        titre: ~
                        description: ~
                        genre: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Element\Personnage
                        provider: ~
                        finder: ~
        inscrit:
        evenement:
        lieu:
        texte:
#        action:
#            index_name: action_%kernel.environment%
#            types:
#                action:
#                    properties:
#                        id: ~
#                        titre: ~
#                    persistence:
#                        driver: orm
#                        model: App\Entity\Concept\Action
#                        provider: ~
#                        finder: ~
