# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default:
            host: '%env(ELASTICA_HOST)%'
            port: '%env(ELASTICA_PORT)%'
            transport: '%env(ELASTICA_TRANSPORT)%'
            headers:
                Authorization: '%env(ELASTICA_AUHTORIZATION)%'

    indexes:
        fiction:
#            index_name: fiction_%kernel.environment%
            types:
                fiction:
                    properties:
                        id: ~
                        titre:
                            type: keyword
                        description: ~
                        uuid: ~
                        projets:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                        textes:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                        inscrit:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                        personnages:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                        evenements:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Concept\Fiction
                        provider: ~
                        finder: ~

        personnage:
            types:
                personnage:
                    properties:
                        id: ~
                        titre:
                            type: keyword
                        nom:
                            type: keyword
                        prenom:
                            type: keyword
                        genre:
                            type: keyword
                        anneeNaissance: ~
                        anneeMort: ~
                        description: ~
                        uuid: ~
                        auto: ~
                        fiction:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Element\Personnage
                        provider: ~
                        finder: ~
        texte:
            types:
                texte:
                    properties:
                        id: ~
                        titre:
                            type: keyword
                        type:
                            type: keyword
                        description: ~
                        uuid: ~
                        fiction:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                titre:
                                    type: keyword
                                description: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Element\Texte
                        provider: ~
                        finder: ~
#        inscrit:
#            index_name: action_%kernel.environment%
#            types:
#                inscrit:
#                    properties:
#                        id: ~
#                        titre: ~
#                    persistence:
#                        driver: orm
#                        model: App\Entity\Concept\Inscrit
#                        provider: ~
#                        finder: ~
