nelmio_api_doc:
    documentation:
        info:
            title: mibu
            description: documentation de l'api de fictio.org
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under / except /doc
